import type { Etude } from '../contracts'

/** The selectable study exercises, in display order. */
export const ETUDES: Etude[] = [
  {
    id: 'relative-minors',
    section: 'Keys & Scales',
    number: 1,
    title: 'Relative Minors',
    subtitle: 'Major keys and their relative minors, on the circle of fifths',
  },
  {
    id: 'scales',
    section: 'Keys & Scales',
    number: 2,
    title: 'Scales',
    subtitle: 'Natural / harmonic / melodic minor scale spellings',
  },
  {
    id: 'fingerings',
    section: 'Keys & Scales',
    number: 3,
    title: 'Scale Fingerings',
    subtitle: 'Two-octave RH & LH fingerings for every minor scale',
    levels: ['Easy', 'Medium', 'Hard'],
  },
  {
    id: 'chords',
    section: 'Chords & Harmony',
    number: 4,
    title: 'Chords by Degree',
    subtitle: 'Diatonic triads (and V7) in every major & minor key',
  },
  {
    id: 'chord-recognition',
    section: 'Chords & Harmony',
    number: 5,
    title: 'Chord Recognition',
    subtitle: 'Read a chord on the staff and name it — against the clock',
    levels: ['Easy', 'Medium', 'Hard'],
  },
  {
    id: 'progressions',
    section: 'Chords & Harmony',
    number: 6,
    title: 'Progressions',
    subtitle: 'Roman-numeral progressions → concrete chords',
  },
  {
    id: 'intervals-ear',
    section: 'Ear Training',
    number: 7,
    title: 'Intervals by Ear',
    subtitle: 'Hear an interval and name it — relative-pitch training',
    levels: ['Easy', 'Medium', 'Hard'],
  },
  {
    id: 'progressions-ear',
    section: 'Ear Training',
    number: 8,
    title: 'Progressions by Ear',
    subtitle: 'Hear a progression over its tonic and name it',
  },
  {
    id: 'melodic-dictation',
    section: 'Ear Training',
    number: 9,
    title: 'Melodic Dictation',
    subtitle: 'Hear a motif over its tonic and name it in solfège',
    levels: ['Easy', 'Medium', 'Hard'],
  },
  {
    id: 'rhythm-dictation',
    section: 'Ear Training',
    number: 10,
    title: 'Rhythm Dictation',
    subtitle: 'Hear a one-bar rhythm and pick the matching notation',
    levels: ['Easy', 'Medium', 'Hard'],
  },
]
